### ISSUE TITLE
Support other LLMs？

### ISSUE THREAD

**Issue by Pythonpa** [xxyQwQ/ComfyBench#2]
Does it support other LLMs? Like 通义千问? Kimi?

**Comment by xxyQwQ** [comment]
Thank you for your questions!

Generating ComfyUI workflows strongly rely on the capabilities of foundation models, so we only implement it using the sota GPT-4o model. With the method improved, some open-source LLMs may be supported in our future work.

If you want to try other LLMs at this time, feel free to modify `utils/llm.py` to implement your own `invoke_completion` function.

**Comment by DnkNju** [comment]
If I want to use Llama-3.1-70B mentioned in the paper, what parts of the code should I modify?

**Comment by xxyQwQ** [comment]
> If I want to use Llama-3.1-70B mentioned in the paper, what parts of the code should I modify?

Modify the `completion` section in `config.yaml`. Set your own `base_url`, `api_key`, and `model_name`.

**Comment by DnkNju** [comment]
Do you mean that Llama-3.1-70B mentioned in the paper is also called through the API instead of being deployed locally?

**Comment by xxyQwQ** [comment]
> Do you mean that Llama-3.1-70B mentioned in the paper is also called through the API instead of being deployed locally?

Yes. There are many ways to deploy your local model into a service, e.g. Ollama and LM Studio.

**Comment by DnkNju** [comment]
> > Do you mean that Llama-3.1-70B mentioned in the paper is also called through the API instead of being deployed locally?
> 
> Yes. There are many ways to deploy your local model into a service, e.g. Ollama and LM Studio.

Thank you for your guidance. Now I have successfully run Llama-3.1-70B in Ollama and it is compatible with the current code. But I would like to ask if there is anything I need to pay attention to when using Llama-3.1-70B? Are there any parameters in the code that need to be modified? Because I used Llama-3.1-70B to test on Benchmark, all 200 data failed and no workflow was produced.

**Comment by xxyQwQ** [comment]
> Thank you for your guidance. Now I have successfully run Llama-3.1-70B in Ollama and it is compatible with the current code. But I would like to ask if there is anything I need to pay attention to when using Llama-3.1-70B? Are there any parameters in the code that need to be modified? Because I used Llama-3.1-70B to test on Benchmark, all 200 data failed and no workflow was produced.

It's strange. You should check the log files and find out which step leads to the failure. Common problems include empty retrieved references and incorrect instruction following.

**Comment by DnkNju** [comment]
> > Thank you for your guidance. Now I have successfully run Llama-3.1-70B in Ollama and it is compatible with the current code. But I would like to ask if there is anything I need to pay attention to when using Llama-3.1-70B? Are there any parameters in the code that need to be modified? Because I used Llama-3.1-70B to test on Benchmark, all 200 data failed and no workflow was produced.
> 
> It's strange. You should check the log files and find out which step leads to the failure. Common problems include empty retrieved references and incorrect instruction following.

Yes, the last line of most logs is "failed to generate workflow: invalid reference" after "-------------------------------- Parsed Action ---------------------------------"

**Comment by xxyQwQ** [comment]
> Yes, the last line of most logs is "failed to generate workflow: invalid reference" after "-------------------------------- Parsed Action ---------------------------------"

RAG relies on an embedding model. Check your embedding API configuration in `config.yaml`.
