### ISSUE TITLE
Any List of Required Models?

### ISSUE THREAD

**Issue by imryanxu** [xxyQwQ/ComfyBench#3]
Thank you for the amazing work on this project! 

While testing some cases using the [meta.json](https://github.com/xxyQwQ/GenAgent/blob/main/dataset/query/meta.json) file, I encountered the following error, which seems to be related to missing models:

```
{"error": {"type": "prompt_outputs_failed_validation", "message": "Prompt outputs failed validation", "details": "", "extra_info": {}}, "node_errors": {"7": {"errors": [{"type": "value_not_in_list", "message": "Value not in list", "details": "ckpt_name: 'dreamshaper_8.safetensors' not in []", "extra_info": {"input_name": "ckpt_name", "input_config": [[], {"tooltip": "The name of the checkpoint (model) to load."}], "received_value": "dreamshaper_8.safetensors"}}], "dependent_outputs": ["2"], "class_type": "CheckpointLoaderSimple"}}}
```

It seems that the checkpoint `dreamshaper_8.safetensors` is missing from the list of available models. Could you please provide a list of the necessary checkpoints that need to be downloaded and placed in the `ComfyUI/models` folder?

Thank you for your assistance!

**Comment by xxyQwQ** [comment]
Currently, only a few frequently-used models are involved in the example workflows. You can check the workflows in `dataset/workflow/raw` and install the used models manually. These models should be easily found by their names on model hubs.

Building a unified environment is of vital importance for automated workflow generation. However, the model specifications of ComfyUI are quite chaotic at present. We will consider this requirement and provide a model list in the future version if necessary.

**Comment by imryanxu** [comment]
Thanks for your response! I have downloaded models according to the raised errors. Now GenAgent is running.
