### ISSUE TITLE
Hi, are the docs of the nodes in your project generated by https://github.com/get-salt-AI/SaltAI_Documentation_Tools? thanks!

### ISSUE THREAD

**Issue by zhoujz10** [xxyQwQ/ComfyBench#5]

**Comment by xxyQwQ** [comment]
Actually, the documentation is directly downloaded from [this repository](https://github.com/get-salt-AI/SaltAI-Web-Docs/tree/main), and processed by `script/build_docs.py`.

In the future version, we will use the API format workflows, and the node templates will be no more useful.

**Comment by zhoujz10** [comment]
> Actually, the documentation is directly downloaded from [this repository](https://github.com/get-salt-AI/SaltAI-Web-Docs/tree/main), and processed by `script/build_docs.py`.
> 
> In the future version, we will use the API format workflows, and the node templates will be no more useful.

Got it, thanks!

**Comment by zhoujz10** [comment]
btw, does the API format workflow refer to the following python API format? If not, where can I can more information about it? thanks!

```
class LoraLoader:
    def __init__(self):
        self.loaded_lora = None

    @classmethod
    def INPUT_TYPES(s):
        return {"required": { "model": ("MODEL",),
                              "clip": ("CLIP", ),
                              "lora_name": (folder_paths.get_filename_list("loras"), ),
                              "strength_model": ("FLOAT", {"default": 1.0, "min": -20.0, "max": 20.0, "step": 0.01}),
                              "strength_clip": ("FLOAT", {"default": 1.0, "min": -20.0, "max": 20.0, "step": 0.01}),
                              }}
    RETURN_TYPES = ("MODEL", "CLIP")
    FUNCTION = "load_lora"

    CATEGORY = "loaders"

    def load_lora(self, model, clip, lora_name, strength_model, strength_clip):
        if strength_model == 0 and strength_clip == 0:
            return (model, clip)

        lora_path = folder_paths.get_full_path("loras", lora_name)
        lora = None
        if self.loaded_lora is not None:
            if self.loaded_lora[0] == lora_path:
                lora = self.loaded_lora[1]
            else:
                temp = self.loaded_lora
                self.loaded_lora = None
                del temp

        if lora is None:
            lora = comfy.utils.load_torch_file(lora_path, safe_load=True)
            self.loaded_lora = (lora_path, lora)

        model_lora, clip_lora = comfy.sd.load_lora_for_models(model, clip, lora, strength_model, strength_clip)
        return (model_lora, clip_lora)```

**Comment by xxyQwQ** [comment]
The API format workflows are JSON files without redundant information, which can be directly executed by ComfyUI API without a frontend interface. For GenAgent, they are closer to the underlying models and can be easily converted into Python code.

It is actually about how ComfyUI works. Refer to [this link](https://github.com/comfyanonymous/ComfyUI/issues/1112) for more information.

**Comment by zhoujz10** [comment]
Got it, thanks
