### ISSUE TITLE
info

### ISSUE THREAD

**Issue by xxd06755** [xxyQwQ/ComfyBench#6]
第一个错误：[2024-10-24 14:54:39] INFO: Failed to generate workflow
failed to generate workflow
---------------------------------------------------------------------------------
第二个错误：Traceback (most recent call last):
  File "C:\code\GenAgent-main\main.py", line 104, in <module>
    main(args)
  File "C:\code\GenAgent-main\main.py", line 79, in main
    workflow = pipeline(args.query_text)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\GenAgent-main\agent\gen_agent\pipeline.py", line 152, in __call__
    raise RuntimeError('Invalid name of reference')
RuntimeError: Invalid name of reference
上述两个错误是运行下面的命令时，有时出现第一个错误，有时出现第二个错误，请问你遇到过吗？如何解决？谢谢！
python main.py \
    --query_text "input your task requirement" \
    --agent_name "gen_agent" \
    --save_path "path/to/save/result"

**Comment by xxyQwQ** [comment]
工作流的生成是有概率失败的，你遇到的错误属于正常现象，可以多尝试几次

你可以通过查看日志的方式，观察生成工作流的具体过程，并确定错误决策出现在哪一步
